'''
This is Assignment 1 written as function (Getting index and value).
>>> L=[10,20,30]
>>> dev_id_search(50,L)
'Found at index: 1'
>>> dev_id_search(20)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: dev_id_search() missing 1 required positional argument: 'dev_list'

'''

def dev_id_search(dev_id, dev_list):
    if dev_id in dev_list:
        return 'Found at index: {}'.format(dev_list.index(dev_id))
    elif dev_id > max(dev_list):
        return 'Not Found'
    else:
        for i in dev_list:
            if i > dev_id:
                return 'Value not found, next highest value-> Index: {}, Value: {}'.format(dev_list.index(i), i)


def main():
    list1 = [1, 3, 5, 16, 8]
    list2 = [6, 5, 9, 4, 13, 12]

    joined_list = list1
    joined_list.extend([x for x in list2 if x not in list1])
    ch = ''
    while ch != 'y':
        id = int(input('Enter Device ID:'))
        print(dev_id_search(id, joined_list))
        ch = input('Exit? ')


if __name__ == '__main__':
    #main()
    import doctest
    doctest.testmod() #executes the docstring(first comment of the program) and checkes whether the output is the same as expected. if same test case passes and process is finished with exit code 0. if not throws an error


O/P:
"C:\Users\lab365\Desktop\Python programming\myvenv1\Scripts\python.exe" C:/Users/lab365/Desktop/python/assignment/assign_1_func.py
**********************************************************************
File "C:/Users/lab365/Desktop/python/assignment/assign_1_func.py", line 4, in __main__
Failed example:
    dev_id_search(50,L)
Expected:
    'Found at index: 1'
Got:
    'Not Found'
**********************************************************************
1 items had failures:
   1 of   3 in __main__
***Test Failed*** 1 failures.

Process finished with exit code 0
